# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  azureSubscription: 'AzureSP2021'
  appName: 'cloud452021app'
  containerRegistry: 'cloud452021.azurecr.io'
  dockerRegistryServiceConnection: 'AzureDockerSP2021'
  imageRepository: 'cloud452021'
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: '$(Build.SourcesDirectory)/StoreAPI/Dockerfile'
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: latest
      env:
        DatabaseSettings__DatabaseName: "CLOUD_45_2021"
        DatabaseSettings__ConnectionString: "mongodb+srv://AdminDenis:DenisMongo@cluster0.sfxuk.mongodb.net/CLOUD_45_2021?retryWrites=true&w=majority"
          ## Add the below snippet at the end of your pipeline
    - task: AzureWebAppContainer@1
      displayName: 'Azure Web App on Container Deploy'
      inputs:
        azureSubscription: $(azureSubscription)
        appName: $(appName)
        containers: $(containerRegistry)/$(imageRepository):latest
